stages:
    - Build
    - Mandatory
build:
    stage: Build
    tags:
        - docker
    script:
        - ./autogen.sh
        - ./configure
        - make
Pre Commit:
    stage: Mandatory
    tags:
        - docker
    script:
        - pre-commit install
        - pre-commit run --all-files
