stages:
    - Build
    - Mandatory
    - Misc
    - Testing
Lines counter:
    stage: Misc
    tags:
        - default
    script:
        - find . -name '*.cc' -o -name '*.hh*' | xargs wc -l
Build:
    stage: Build
    tags:
        - default
    script:
        - ./autogen.sh
        - ./configure
        - make -j4
Pre Commit:
    stage: Mandatory
    tags:
        - default
    script:
        - pre-commit install
        - pre-commit run --all-files
Stress Test:
    stage: Testing
    tags:
        - default
    script:
        - ./autogen.sh
        - ./configure
        - make -j4
        - ./spider tests/config_tests/config_file.json &
        - siege --reps=10000 127.0.0.1:8000
