stages:
    - Build
    - Mandatory
    - Misc
Lines counter:
    stage: Misc
    tags:
        - default
    script:
        - find . -name '*.cc' -o -name '*.hh*' | xargs wc -l
Build:
    stage: Build
    tags:
        - default
    script:
        - ./autogen.sh
        - ./configure
        - make
Pre Commit:
    stage: Mandatory
    tags:
        - default
    script:
        - pre-commit install
        - pre-commit run --all-files
